spring.application.name=td1

server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/td1_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Configuration SOAP Service
soap.service.url=http://localhost:8081/ws

# Configuration Middle-Service REST
middle.service.url=http://localhost:8081/api/servers
